package greeter

var BirthdayGreetings = []string{
	"Happy birthday <<nickname>>! Praying God fills this year with His joy and peace. May you feel His presence in every moment. Have an amazing day! Love, from your Dgroup family",
	"Wishing you the happiest birthday <<nickname>>! May God's blessings overflow in your life today and always. You're such a gift to everyone around you! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May He continue to guide your steps and give you strength for whatever comes your way. Love, from your Dgroup family",
	"Hope your birthday is as wonderful as you are <<nickname>>! Praying this new year brings you closer to God's heart and all the dreams He has for you. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May the Lord surround you with His love today and grant you many more years of health and happiness. Celebrate big! Love, from your Dgroup family",
	"Sending you birthday blessings <<nickname>>! God has great plans for you this year. May all the amazing things He's going to do in your life unfold beautifully! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! You're a true blessing, and may God surprise you with His goodness today. Enjoy every moment of your special day! Love, from your Dgroup family",
	"Wishing you a blessed birthday filled with laughter and joy <<nickname>>! May God's grace shine on you today and throughout the coming year. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! Remember, you're fearfully and wonderfully made. Praying this year brings new adventures and deeper faith. Have a blast! Love, from your Dgroup family",
	"Another year of God's faithfulness! Happy birthday <<nickname>>. May He give you wisdom, joy, and all the desires of your heart as you walk with Him. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! Praying He blesses you beyond measure and fills your day with sweet memories. Love, from your Dgroup family",
	"Wishing you the best birthday ever <<nickname>>! May God's love surround you, His peace guard your heart, and His joy be your strength this year. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! Praying Jeremiah 29:11 over you today - that God's plans for you are full of hope and a bright future. Celebrate well! Love, from your Dgroup family",
	"Hope your birthday is absolutely blessed <<nickname>>! May God continue to use you in mighty ways and shower you with His favor. You deserve the best! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May this year be your best one yet and may you continue to reflect His love in all you do! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May God's love be the foundation of your year ahead. Praying for His guidance and blessings in every step you take. Love, from your Dgroup family",
	"Wishing you a joyful birthday <<nickname>>! May the Lord's presence be with you today and always, filling your life with peace and happiness. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May God's grace abound in your life this year, bringing you closer to Him and fulfilling all the desires of your heart. Love, from your Dgroup family",
	"Hope your birthday is as amazing as you are <<nickname>>! Praying that God continues to bless you with good health, strong faith, and wonderful opportunities. Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May the Lord bless you with many more years of love, laughter, and cherished memories. You're a true blessing to everyone around you! Love, from your Dgroup family",
	"Wishing you the happiest birthday <<nickname>>! May God's blessings overflow in your life today and always. You're such a gift to everyone around you! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May God's love surround you today and always, filling your life with joy and peace. Have an amazing day! Love, from your Dgroup family",
	"Sending you birthday blessings <<nickname>>! May the Lord surround you with His love today and grant you many more years of health and happiness. Celebrate big! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May the Lord bless you with many more years of love, laughter, and cherished memories together. You're an inspiration! Love, from your Dgroup family",
	"Wishing you the happiest birthday <<nickname>>! May God's blessings overflow in your life today and always. You're such a gift to everyone around you! Love, from your Dgroup family",
	"Happy birthday <<nickname>>! May God's love surround you today and always, filling your life with joy and peace. Have an amazing day! Love, from your Dgroup family",
}

var WeddingAnniversaryGreetings = []string{
	"Happy Anniversary Team <<lastName>>! May God continue to bless your marriage with love, joy, and unity. Celebrating the beautiful journey He has you on together! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Praying that your love grows deeper with each passing year and that God's grace continues to strengthen your bond. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! What a blessing to witness the love you share. May the Lord fill your home with laughter and your hearts with His peace. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May God's love be the foundation of your marriage today and always. Here's to many more years of His faithfulness! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Celebrating the covenant you've made before God. Praying He continues to guide you both and bless your union abundantly. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Two hearts, one faith, endless blessings. May God's hand be upon your marriage now and forever. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May the Lord continue to write beautiful chapters in your love story. Grateful for the example of Christ-centered love you both show! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Praying Ecclesiastes 4:12 over your marriage - that your threefold cord with God may never be broken. Celebrate big! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May God bless you with many more years of love, laughter, and cherished memories together. You're an inspiration! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Thanking God for bringing you two together and for the amazing testimony of faith and love your marriage is. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May your love continue to reflect God's unconditional love. Praying for strength, joy, and countless blessings in the years ahead. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Another year of growing together in faith and love. May God's presence be felt in every moment you share. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Celebrating the beautiful partnership God has blessed you with. May He continue to pour out His favor on your marriage! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Praying your marriage continues to be anchored in faith, hope, and love. May God grant you many more wonderful years together! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! What a joy to see how God works through your love for each other. May He bless this special day and all the days to come! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May the Lord's blessings continue to overflow in your marriage, bringing you closer together and closer to Him. Celebrate well! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May God's love be the foundation of your marriage today and always. Here's to many more years of His faithfulness! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Praying Ecclesiastes 4:12 over your marriage - that your threefold cord with God may never be broken. Celebrate big! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May God bless you with many more years of love, laughter, and cherished memories together. You're an inspiration! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Thanking God for bringing you two together and for the amazing testimony of faith and love your marriage is. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May your love continue to reflect God's unconditional love. Praying for strength, joy, and countless blessings in the years ahead. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Another year of growing together in faith and love. May God's presence be felt in every moment you share. Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Celebrating the beautiful partnership God has blessed you with. May He continue to pour out His favor on your marriage! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! Praying your marriage continues to be anchored in faith, hope, and love. May God grant you many more wonderful years together! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! What a joy to see how God works through your love for each other. May He bless this special day and all the days to come! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May the Lord's blessings continue to overflow in your marriage, bringing you closer together and closer to Him. Celebrate well! Love, from your Dgroup family",
	"Happy Anniversary Team <<lastName>>! May God's love be the foundation of your marriage today and always. Here's to many more years of His faithfulness! Love, from your Dgroup family",
}
